# Generated by Django 5.2.10 on 2026-01-18 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('url', models.URLField(max_length=256, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
                'db_table': 'feed',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('guid', models.CharField(max_length=32, verbose_name='GUID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('link', models.URLField(max_length=256, verbose_name='Link')),
                ('author', models.CharField(blank=True, default='', max_length=32, verbose_name='Author')),
                ('enclosure_url', models.URLField(blank=True, default='', max_length=256, verbose_name='Enclosure URL')),
                ('enclosure_type', models.CharField(blank=True, default='', max_length=32, verbose_name='Enclosure type')),
                ('published', models.DateTimeField(db_index=True, verbose_name='Published')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.feed', verbose_name='Feed')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Hidden'), (2, 'Bookmark')], default=1, verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='news.news', verbose_name='News')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
                'db_table': 'mark',
            },
        ),
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('title', models.CharField(blank=True, default='', max_length=64, verbose_name='Title')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfeeds', to='news.feed', verbose_name='Feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User feed',
                'verbose_name_plural': 'User feeds',
                'db_table': 'user_feed',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('entry', models.CharField(max_length=32, verbose_name='Entry')),
                ('part', models.CharField(choices=[('start', 'Beginning of a word'), ('end', 'End of a word'), ('full', 'Whole word'), ('part', 'Any part of a word')], default='start', max_length=8, verbose_name='Part of a word')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsfilters', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsfilters', to='news.userfeed', verbose_name='Feed')),
            ],
            options={
                'verbose_name': 'News filter',
                'verbose_name_plural': 'News filters',
                'db_table': 'filter',
                'ordering': ('-created',),
            },
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['created'], name='news_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('feed', 'guid'), name='unique_feed_guid'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['created'], name='mark_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('user', 'news'), name='unique_user_news'),
        ),
        migrations.AddIndex(
            model_name='userfeed',
            index=models.Index(fields=['created'], name='userfeed_created_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['user', 'feed'], name='filter_user_feed_idx'),
        ),
    ]
