# Generated by Django 5.1.7 on 2025-04-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='task_db_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path='taskstorage', recursive=True, verbose_name='TaskWarrior database path'),
        ),
    ]
